### ISSUE TITLE
[help] Is there any XC-20s Cross-Chain Transfer tutorial doc with local machine enviroment

### ISSUE THREAD

**Issue by AlexiaChen** [PureStake/moonbeam-docs#416]
I browsed Moonbeam's official documentation and found a XC-20 tutorial for cross-chain transfers https://docs.moonbeam.network/builders/xcm/xc20/xtokens/ but it was taught using Moonbeam Alphanet's environment and did not use https://github.com/PureStake/moonbeam/tree/master/tools link to set up transfers between local parachains.  Instead, my local environment was launched with the command `npm run launch -- --parachain moonbase-0.26.0 --parachain moonbase-0.26.0` My ultimate goal is that I need to test XC-20 transfers on my local machine（no public IP）, how should I do this?

Thanks!

**Comment by albertov19** [comment]
Hey @AlexiaChen  - This is not straightforward at all because you'll need to launch the parachain-relay chain, then register the assets through governance (and HRMP channels if needed) and then follow the tutorials.

My guess is that the problem lies in the first part rather, but the tutorial is still holds just changing the RPC endpoint

**Comment by AlexiaChen** [comment]
> Hey @AlexiaChen  - This is not straightforward at all because you'll need to launch the parachain-relay chain, then register the assets through governance (and HRMP channels if needed) and then follow the tutorials.
> 
> My guess is that the problem lies in the first part rather, but the tutorial is still holds just changing the RPC endpoint

thanks,anyway.
